[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = {version ="2.2.4" , features = ["sqlite" ]}
diesel_migrations = { version = "2.2.0", features = ["sqlite" ] }


dirs = "5.0.1"
dotenvy = "0.15"
