[package]
name = "account"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }

database = { path = "../database" }
blockchain = { path = "../blockchain" }
